name: surya_namaskar
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Gym_.jpg
    - assets/images/yoga_.jpg
    - assets/images/Suryanamaskar_.jpg
    - assets/images/Surya-Namaskar-step-1.jpg
    - assets/images/Surya-Namaskar-step-2.jpg
    - assets/images/Surya-Namaskar-step-3.jpg
    - assets/images/Surya-Namaskar-step-4.jpg
    - assets/images/Surya-Namaskar-step-5.jpg
    - assets/images/Surya-Namaskar-step-6.jpg
    - assets/images/Surya-Namaskar-step-7.jpg
    - assets/images/Surya-Namaskar-step-8.jpg
    - assets/images/Surya-Namaskar-step-9.jpg
    - assets/images/Surya-Namaskar-step-10.jpg
    - assets/images/Surya-Namaskar-step-11.jpg
    - assets/images/Surya-Namaskar-step-12.jpg

    - assets/images/yoga1.webp
    - assets/images/yoga2.webp
    - assets/images/yoga3.webp
    - assets/images/yoga4.png
    - assets/images/yoga5.jpg
    - assets/images/yoga6.png
    - assets/images/yoga7.jpg
    - assets/images/yoga8.jpg
    - assets/images/yoga9.jpg
    - assets/images/yoga10.webp
    - assets/images/yoga11.jpg
    - assets/images/yoga12.jpg
    - assets/images/yoga13.jpg
    - assets/images/yoga14.jpg
    - assets/images/yoga15.jpg
    - assets/images/yoga16.webp
    - assets/images/yoga17.jpg
    - assets/images/yoga18.jpg
    - assets/images/yoga19.webp
    - assets/images/yoga20.jpg
    - assets/images/yoga21.webp
    - assets/images/yoga22.webp
    - assets/images/yoga23.webp
    - assets/images/yoga24.webp
    - assets/images/yoga25.webp
    - assets/images/yoga26.webp
    - assets/images/yoga27.webp
    - assets/images/yoga28.webp
    - assets/images/yoga29.webp
    - assets/images/yoga30.jpg
    - assets/images/yoga31.webp

    - assets/images/gym1.jpg
    - assets/images/gym2.jpg
    - assets/images/gym3.jpg
    - assets/images/gym4.jpg
    - assets/images/gym5.jpg
    - assets/images/gym6.jpg
    - assets/images/gym7.jpg
    - assets/images/gym8.jpg
    - assets/images/gym9.jpg
    - assets/images/gym10.jpg
    - assets/images/gym11.jpg
    - assets/images/gym12.png
    - assets/images/gym13.jpg
    - assets/images/gym14.jpg
    - assets/images/gym15.jpg
    - assets/images/gym16.jpg
    - assets/images/gym17.jpg
    - assets/images/gym18.jpg
    - assets/images/gym19.jpg
    - assets/images/gym20.jpg
    - assets/images/gym21.jpg
    - assets/images/gym22.jpg
    - assets/images/gym23.jpg
    - assets/images/gym24.jpg
    - assets/images/gym25.png
    - assets/images/gym26.jpg
    - assets/images/gym27.jpg
    - assets/images/gym28.jpg
    - assets/images/gym29.jpg
    - assets/images/gym30.jpg
    - assets/images/gym31.jpg
    - assets/images/gym32.jpg





  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
