class Fitness_data {
  static List surya_namaskar = [
    "Surya-Namaskar-step-1.jpg",
    "Surya-Namaskar-step-2.jpg",
    "Surya-Namaskar-step-3.jpg",
    "Surya-Namaskar-step-4.jpg",
    "Surya-Namaskar-step-5.jpg",
    "Surya-Namaskar-step-6.jpg",
    "Surya-Namaskar-step-7.jpg",
    "Surya-Namaskar-step-8.jpg",
    "Surya-Namaskar-step-9.jpg",
    "Surya-Namaskar-step-10.jpg",
    "Surya-Namaskar-step-10.jpg",
    "Surya-Namaskar-step-10.jpg"
  ];
  static List surya_namaskar_name = [
    "Pranamasana\nPrayer pose",
    "Hastauttanasana\nRaised arms pose",
    "Hastapadasana\nStanding forward bend",
    "Ashwa Sanchalanasana\nEquestrian pose",
    "Dandasana\nStick pose",
    " Ashtanga Namaskara\nSalute with eight \nparts or points",
    "Bhujangasana\nCobra pose",
    "Adho Mukha Svanasana\nDownward facing dog pose",
    "Ashwa Sanchalanasana\nEquestrian pose",
    "Hastapadasana\nStanding forward bend",
    "Hastauttanasana\nRaised arms pose",
    "Tadasana\nMountain Pose"
  ];

  static List yoga_Steps_name = [
    "Downward Facing Dog\nAdho Mukha Svanasana",
    "Mountain Pose \nTadasana",
    "Warrior I \nVirabhadrasana I",
    "Warrior II \nVirabhadrasana II",
    "Extended Side Angle \nUtthita Parvakonasana",
    "Triangle Pose \nUtthita Trikonasana",
    "Standing Forward Bend \nUttanasana",
    "Reverse Warrior \nViparita Virabhadrasana",
    "Garland Pose \nMalasana",
    "Half Forward Bend \nArdha Uttanasana",
    "Pyramid Pose \nParsvottanasana",
    "Raised Hands Pose \nUrdhva Hastasana",
    "Low Lunge",
    "Tree Pose \nVrksasana",
    "Downward Facing Dog Split",
    "Plank Pose",
    "Cat-Cow Stretch \nChakravakasana",
    "Bridge Pose \nSetu Bandha Sarvangasana",
    "Cobra Pose \nBhujangasana",
    "Knees, Chest, and Chin \nAshtanga Namaskara",
    "Staff Pose \nDandasana",
    "Cobbler's Pose \nBaddha Konasana",
    "Easy Pose \nSukhasana",
    "Half Lord of the Fishes Pose \nArdha Matsyendrasana",
    "Head to Knee Pose \nJanu Sirsasana",
    "Seated Forward Bend \nPaschimottanasana",
    "Seated Wide Angle Straddle \nUpavistha Konasana",
    "Happy Baby Pose \nAnanda Balasana",
    "Supine Spinal Twist \nSupta Matsyendrasana",
    "Child's Pose \nBalasana",
    "Corpse Pose \nSavasana",
  ];
  static List yoga_image = [
    "yoga1.webp",
    "yoga2.webp",
    "yoga3.webp",
    "yoga4.png",
    "yoga5.jpg",
    "yoga6.png",
    "yoga7.jpg",
    "yoga8.jpg",
    "yoga9.jpg",
    "yoga10.webp",
    "yoga11.jpg",
    "yoga12.jpg",
    "yoga13.jpg",
    "yoga14.jpg",
    "yoga15.jpg",
    "yoga16.webp",
    "yoga17.jpg",
    "yoga18.jpg",
    "yoga19.webp",
    "yoga20.jpg",
    "yoga21.webp",
    "yoga22.webp",
    "yoga23.webp",
    "yoga24.webp",
    "yoga25.webp",
    "yoga26.webp",
    "yoga27.webp",
    "yoga28.webp",
    "yoga29.webp",
    "yoga30.jpg",
    "yoga31.webp",
  ];

  static List Gym_image = [
    "gym1.jpg",
    "gym2.jpg",
    "gym3.jpg",
    "gym4.jpg",
    "gym5.jpg",
    "gym6.jpg",
    "gym7.jpg",
    "gym8.jpg",
    "gym9.jpg",
    "gym10.jpg",
    "gym11.jpg",
    "gym12.png",
    "gym13.jpg",
    "gym14.jpg",
    "gym15.jpg",
    "gym16.jpg",
    "gym17.jpg",
    "gym18.jpg",
    "gym19.jpg",
    "gym20.jpg",
    "gym21.jpg",
    "gym22.jpg",
    "gym23.jpg",
    "gym24.jpg",
    "gym25.png",
    "gym26.jpg",
    "gym27.jpg",
    "gym28.jpg",
    "gym29.jpg",
    "gym30.jpg",
    "gym31.jpg",
    "gym32.jpg",
  ];
  static List Gym_steps_name = [
    "Push-up",
    "Feet elevated push-up",
    "Hands elevated push-up",
    "Close-grip Push-up",
    "Pike push-up",
    "Bench/box dip",
    "Burpee",
    "Strict handstand push-up",
    "Air squat",
    "Jump squat",
    "Forward lunge",
    "Split Squat jump",
    "Pistol squat",
    "Cyclist squat",
    "Butterfly sit-up",
    "Mountain climber",
    "Straight arm plank",
    "Plank shoulder tap",
    "Pull-up",
    "Chin-up",
    "Ring\n Suspension Trainer Row",
    "Ring\n suspension trainer dip",
    "Ring\n suspension trainer push-ups",
    "Hanging knees raises",
    "Standing Shoulder Press",
    "Push press",
    "Single arm push press",
    "Z-press",
    "Floor press",
    "Upright row",
    "Bent-over row",
    "Three point row",
  ];
}
